### ISSUE TITLE
Track open issues in other projects

### ISSUE THREAD

**Issue by hepabolu** [bartificer/taming-the-terminal#29]
The sole purpose for this issue is to track issues I opened in other projects, so I have all of them together and don't have to hunt my ginormous list of open tabs.

- [x] Vale project, ignore variables: https://github.com/errata-ai/vale-action/issues/11
- [ ] Asciidoctor, Rouge, linenums: https://github.com/asciidoctor/asciidoctor/issues/3641

Tracking other interesting issues as well
- [ ] index in ePub: https://github.com/asciidoctor/asciidoctor-epub3/issues/168
- [ ] index in HTML: https://github.com/asciidoctor/asciidoctor/issues/450
- [x] remote urls in ePub manifest: https://github.com/asciidoctor/asciidoctor-epub3/issues/334
